//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallNoteComment
    {
        public int WallNoteCommentID { get; set; }
        public int UserId { get; set; }
        public int WallNoteId { get; set; }
        public string CommentBody { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
